# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_deps_memo <- function(from, to, pkg) {
    .Call(`_havel_get_deps_memo`, from, to, pkg)
}

get_region <- function(abs_th, p2_th, p2_high, pi) {
    .Call(`_havel_get_region`, abs_th, p2_th, p2_high, pi)
}

get_axy <- function(reg, xs, xe, ys, ye, th, p2x, p2y) {
    .Call(`_havel_get_axy`, reg, xs, xe, ys, ye, th, p2x, p2y)
}

stress <- function(x, D) {
    .Call(`_havel_stress`, x, D)
}

stress_layout <- function(y, D, iter, tol) {
    .Call(`_havel_stress_layout`, y, D, iter, tol)
}

